CREATE DATABASE Quinielas

GO

USE Quinielas

GO

CREATE TABLE Temporadas
(
	ID INT NOT NULL,
	Numero INT NOT NULL,

	CONSTRAINT PK_Temporadas PRIMARY KEY (ID)
)



GO

CREATE TABLE Jornadas
(
	ID INT NOT NULL,
	Fecha DATE NOT NULL,
	IDTemporada INT

	CONSTRAINT PK_Jornadas PRIMARY KEY (ID),
	CONSTRAINT FK_Jornadas_Temporadas FOREIGN KEY (IDTemporada) REFERENCES Temporadas (ID) ON UPDATE CASCADE ON DELETE NO ACTION
)

CREATE TABLE Sorteos
(
	ID INT NOT NULL,

	CONSTRAINT PK_Sorteo PRIMARY KEY (ID)
)

GO
CREATE TABLE Boletos
(
	ID INT NOT NULL,
	IDJornada INT NOT NULL,
	IDSorteo INT NOT NULL,

	CONSTRAINT PK_Boletos PRIMARY KEY (ID), -- Pensar más atributos
	CONSTRAINT FK_Boletos_Jornadas FOREIGN KEY (IDJornada) REFERENCES Jornadas (ID) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT FK_Boletos_Sorteos FOREIGN KEY (IDSorteo) REFERENCES Sorteos (ID) ON UPDATE CASCADE ON DELETE NO ACTION
)

GO


CREATE TABLE Partidos
(
	ID INT NOT NULL,
	Equipo1 VARCHAR (50) NOT NULL,
	Equipo2 VARCHAR (50) NOT NULL,
	Resultado VARCHAR (3) NULL,
	IDJornada INT NOT NULL,
	
	CONSTRAINT PK_Partidos PRIMARY KEY (ID),
	CONSTRAINT FK_Partidos_Jornadas FOREIGN KEY (IDJornada) REFERENCES Jornadas (ID) ON UPDATE CASCADE ON DELETE NO ACTION
)

GO


GO

CREATE TABLE Apuestas
(
	ID INT NOT NULL,
	IDBoleto INT NOT NULL,
	Valor DECIMAL (6,2) NOT NULL,
	Prediccion1 VARCHAR (3) NOT NULL,
	Prediccion2 VARCHAR (3) NOT NULL,
	Prediccion3 VARCHAR (3) NOT NULL,
	Prediccion4 VARCHAR (3) NOT NULL,
	Prediccion5 VARCHAR (3) NOT NULL,
	Prediccion6 VARCHAR (3) NOT NULL,
	Prediccion7 VARCHAR (3) NOT NULL,
	Prediccion8 VARCHAR (3) NOT NULL,
	Prediccion9 VARCHAR (3) NOT NULL,
	Prediccion10 VARCHAR (3) NOT NULL,
	Prediccion11 VARCHAR (3) NOT NULL,
	Prediccion12 VARCHAR (3) NOT NULL,
	Prediccion13 VARCHAR (3) NOT NULL,
	Prediccion14 VARCHAR (3) NOT NULL,
	PrediccionPleno VARCHAR (4) NULL,

	CONSTRAINT PK_Apuesta PRIMARY KEY (ID, IDBoleto),
	CONSTRAINT FK_Apuestas_Boletos FOREIGN KEY (IDBoleto) REFERENCES Boletos (ID) ON UPDATE CASCADE ON DELETE CASCADE
)

GO

CREATE TABLE Boletos_Partidos
(
	IDBoleto INT NOT NULL,
	IDPartido INT NOT NULL,

	CONSTRAINT PK_Boletos_Partidos PRIMARY KEY (IDBoleto, IDPartido),
	CONSTRAINT FK_Boletos_Partidos_Boletos FOREIGN KEY (IDBoleto) REFERENCES Boletos (ID) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT FK_Boletos_Partidos_Partidos FOREIGN KEY (IDPartido) REFERENCES Partidos (ID) ON UPDATE NO ACTION ON DELETE NO ACTION --Cambiar estos dos update y cascade
)
